repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: 'helm/charts/.*/templates/.*\.yaml$'
  - repo: local
    hooks:
      - id: yaml-check
        name: Check YAML syntax
        entry: python3 -c "import yaml; import sys; [yaml.safe_load(open(f)) for f in sys.argv[1:]]"
        language: system
        files: \.ya?ml$
        exclude: 'helm/charts/.*/templates/.*\.yaml$'
