apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: default-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:2.7
        ports:
        - containerPort: 8086
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: "setup"
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: "admin"
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: "admin123" # for local development only, do not use in production
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: "monitoring"
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: "telegraf"
        volumeMounts:
        - name: influxdb-storage
          mountPath: /var/lib/influxdb2
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: default-apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: default-apps
spec:
  selector:
    app: influxdb
  ports:
  - port: 8086
    targetPort: 8086
    nodePort: 30300
  type: NodePort
