# terraform-specific values
namespace: "default-apps"

cluster:
  name: "dev-cluster"
  image: "kindest/node:v1.33.0"
  ports:
    grafana: 30080
    influxdb: 30300
    api: 30090

storage:
  influxdb: "10Gi"
  grafana: "5Gi"

database_name: "telegraf"
# for local development only, do not use in production
# in a production environment we will use secrets manager secured credentials utilising versioning
grafana_password: "admin"
