---
configuration:
  # File paths
  parts:
    # shared configuration values
    shared:
      tags: k8s-cluster/dev/shared/tags.yaml
      secrets: k8s-cluster/dev/shared/secrets.yaml

    # terraform configuration
    terraform:
      backend:
        local: k8s-cluster/dev/terraform/backend/local.tfvars.json
      parts:
        root: k8s-cluster/dev/terraform/terraform.yaml

    # helm configuration
    helm:
      root: k8s-cluster/dev/helm/helm.yaml
