---
configuration:
  # File paths
  parts:
    shared: k8s-cluster/dev/shared/common-values.yaml
    
    terraform:
      backend:
        local: k8s-cluster/dev/terraform/backend/local.tfvars.json
      parts:
        root: k8s-cluster/dev/terraform/terraform.yaml
        tags:
          common: common/tags.yaml
          project: k8s-cluster/dev/tags.yaml
        secrets:
          common: common/secrets.yaml
          project: k8s-cluster/dev/secrets.yaml

    helm:
      root: k8s-cluster/dev/helm/helm.yaml