---
configuration:
  metadata:
    structure:
      root: k8s-cluster/dev/configuration.yaml

      terraform:
        backend:
          local: k8s-cluster/dev/terraform/backend/local.tfvars.json

        includes:
          root: k8s-cluster/dev/terraform/terraform.yaml
          tags: k8s-cluster/dev/shared/tags.yaml
          secrets: k8s-cluster/dev/shared/secrets.yaml

      helm:
        includes:
          root: k8s-cluster/dev/helm/helm.yaml
